spring:
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  profiles:
    active: dev
#  main:
#    allow-circular-references: true
#  datasource:
#    driver-class-name: ${birdblog.datasource.driver-class-name}
#    url: jdbc:mysql://${birdblog.datasource.host}:${birdblog.datasource.port}/${birdblog.datasource.database}
#    username: ${birdblog.datasource.username}
#    password: ${birdblog.datasource.password}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs

knife4j:
  enable: true
  setting:
    language: zh_cn

birdblog:
  alioss:
    endpoint: ${birdblog.alioss.endpoint}
    bucket-name: ${birdblog.alioss.bucket-name}
    region: ${birdblog.alioss.region}

