birdblog:
  alioss:
    endpoint: "https://oss-cn-guangzhou.aliyuncs.com"
    bucket-name: typora-birdy
    region: cn-guangzhou

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: birdblog
    username: root
    password: root